#! /bin/bash
[[ -z "${DEBUG:-}" ]] || set -x
set -eu

if grep -e '^  - "--encryption-provider-config=.*$' /var/vcap/jobs/kube-apiserver/config/bpm.yml;
then
    sed -ie \
        's|^  - "--encryption-provider-config=.*$|  - "--encryption-provider-config=/var/vcap/jobs/encryption-provider-config/config/encryption-config.yml"|g' \
        /var/vcap/jobs/kube-apiserver/config/bpm.yml
else
    sed -ie \
        's|^  args:.*$|&\n  - "--encryption-provider-config=/var/vcap/jobs/encryption-provider-config/config/encryption-config.yml"|g' \
        /var/vcap/jobs/kube-apiserver/config/bpm.yml
fi

